# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V0cdDBFv1AgfthZ1ZC2gInmVAcBJM9rZ
"""

import streamlit as st
from transformers import pipeline
import pyttsx3
import os

# -----------------------------
# 1. Set Hugging Face token
# -----------------------------
os.environ["HUGGINGFACEHUB_API_TOKEN"] = "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"

# -----------------------------
# 2. PAGE SETUP
# -----------------------------
st.set_page_config(page_title="Persona VoiceBot", layout="centered", page_icon="🎤")
st.title("🎤 Persona VoiceBot — Hugging Face Edition")
st.write("Ask questions, and the bot will respond like YOU.")

# -----------------------------
# 3. Define your persona (full version)
# -----------------------------
persona_prompt = """
I am a very hardworking person. I do not easily give up when the situations are worse.
I achieve my goals, complete my works and duties even how hard it takes to reach up anywhere.
So to sum up, I can say I am not a quitter. But an evolving person who tries to learn from my situations and duties.

Focused learning. I am a person who can get my complete focus when I am trying to learn something or do my work.

The 3 areas which I wish to improve myself are my leadership qualities, my memory skills, and multitasking abilities.

A common misconception my classmates have against me is that things come easier to me or go smoothly
without any obstacles. But the reality is different. I do face obstacles and every day is a challenge.

In order to push my boundaries and limits, I keep a track of what all things should be done and act.
If the tasks have a possibility of overwhelming I mould myself according to that. I finish off my day-to-day work without keeping anything left for the day.
I am a person who prefers to complete my duties without procrastination.
"""

# -----------------------------
# 4. Load Hugging Face model (lightweight version)
# -----------------------------
generator = pipeline(
    "text-generation",
    model="distilgpt2",  # lightweight model for free tier
    use_auth_token=True
)

# -----------------------------
# 5. User input
# -----------------------------
question = st.text_input("Ask your question:")

if st.button("Submit") and question.strip():
    # Combine persona + user question
    prompt = persona_prompt + "\nQuestion: " + question + "\nAnswer:"

    # Generate answer (shorter output for free tier)
    output = generator(
        prompt,
        max_length=100,  # shorter for Streamlit free tier
        do_sample=True,
        temperature=0.7
    )[0]['generated_text']

    # Extract the answer portion only
    answer = output.replace(prompt, "").strip()

    st.write("**VoiceBot Response:**", answer)

    # Optional: text-to-speech
    engine = pyttsx3.init()
    engine.say(answer)
    engine.runAndWait()

